### ISSUE TITLE
Small QR core

### ISSUE THREAD

**Issue by PLipski1** [philipptrenz/covidpass#52] opened 2021-12-02 16:28 UTC
Hello I have used your website to add my covid cert to apple walet. I’m using iphone11 and certificate is generated by polish e-zdrowie.
I see an issue that QR code in wallet page is to small and scanner which is installed on another phone can’t read it. Have you tested that it is ok?

**Comment by philipptrenz** [comment] 2021-12-02 17:22
Hi @PLipski1, this is a duplicate of #32.

TL;DR: We are aware that some scanners or smartphones have difficulties scanning the QR Code, but on the majority of devices it seems to work fine. Unfortunately Apple does not provide any way to control the size of the QR Code, so that we cannot do anything about that. Sorry!

**Closed by philipptrenz** 2021-12-02 17:22 UTC
