### ISSUE TITLE
Cannot remove outdated pass

### ISSUE THREAD

**Issue by PeteNieminen** [philipptrenz/covidpass#62] opened 2022-01-07 08:53 UTC
On iPhone 12 Pro, iOS 15.1 and iOS 15.2 one cannot remove the old outdates covid-pass from the wallet.

Hitting "the three dots" on wallet pass, displays only the pass and application information, but no any
options - including the missing "Remove pass" option.

Only way to remove the pass and replace it with a new one is to completely erase the phone which removes
everything from the wallet too.

**Comment by philipptrenz** [comment] 2022-01-07 09:35
Hi @PeteNieminen, 
please check out the second FAQ at https://covidpass.eu/faq and make sure you're using the Wallet App (so that the three dots are at the top right) and not opening the wallet by double-tapping (where the dots are shown at the bottom right).

**Comment by PeteNieminen** [comment] 2022-01-07 10:06
Yes, after the dots all I get is this. ![image](https://user-images.githubusercontent.com/97282269/148528027-0878e6ae-8a5b-4f35-ab4a-d5a20ef89e6f.jpeg)

**Comment by PeteNieminen** [comment] 2022-01-07 10:13
Ok, played with my Mac and put iOS 15.1 back again. Now it worked via the app!

**Comment by philipptrenz** [comment] 2022-01-07 10:28
Glad you found a solution!
It seems to be a bug within iOS 15.2, although it works fine on my device with iOS 15.2. I'll close this issue, as the issue is on Apples side and there's nothing we could do about it.

**Closed by philipptrenz** 2022-01-07 10:28 UTC
Labels: bug
