### ISSUE TITLE
QR code size in Apple Wallet is too small for Finnish COVID pass

### ISSUE THREAD

**Issue by novakbandi** [philipptrenz/covidpass#51] opened 2021-12-02 11:50 UTC
Makes it difficult to read with another phone's camera. Simply increasing the size of the QR code would help.

**Comment by PLipski1** [comment] 2021-12-02 16:29
Same same issue for Polish QR.

**Comment by philipptrenz** [comment] 2021-12-02 17:23
Hi @novakbandi , this is a duplicate of #32.

TL;DR: We are aware that some scanners or smartphones have difficulties scanning the QR Code, but on the majority of devices it seems to work fine. Unfortunately Apple does not provide any way to control the size of the QR Code, so that we cannot do anything about that. Sorry!

@donatuswolf can you please add this to our FAQ page?

**Closed by philipptrenz** 2021-12-02 17:23 UTC
Labels: duplicate
