### ISSUE TITLE
Cannot validate the QR code

### ISSUE THREAD

**Issue by SigritSiht** [philipptrenz/covidpass#28] opened 2021-07-29 13:34 UTC
I have two devices (iPhone 12 Mini and XR)
I added the COVID Pass to my Wallet (not relevant to this issue, but it for some reason doesn't work with Chrome and only allows to add it to Wallet using Safari (iPhone XR didn't try with 12M.)

My certificate is Estonian and for vaccination. The actual issue for me for both phones is that I cannot scan the QR code because of low resolution maybe? Thanks to  https://kontroll.digilugu.ee/ we can check for validity of the QR code and I cannot get it to read the QR code.

**Comment by philipptrenz** [comment] 2021-08-13 16:51
Duplicate of #32

**Closed by philipptrenz** 2021-08-13 16:51 UTC
Labels: duplicate
